### ISSUE TITLE
REST services documentation

### ISSUE THREAD

**Issue by mfarees** [codingfriend1/Feathers-Vue#7]
Is there a documentation on how to use the REST services? I'm stuck on Logout and Forget Password requests.

**Comment by codingfriend1** [comment]
I've added a message parameter for the logout request and if you pass in a message it will display it when logging out. It should work as expected now.

As for the forget password request, in the login form you must first type in your email and then hit forgot password. Also do you have your gmail credentials set in environment variables?

**Comment by mfarees** [comment]
I'm sorry but I should have mentioned I'm trying to achieve this via REST services. I have my own frontend client set up, but I'm using FeathersJS in the backend. I want to logout and reset password via REST services. Yes, I've set the Gmail email and password in the environment variables and it's working great in your app. Can you help out with REST?

**Comment by codingfriend1** [comment]
If you want to see a request being made, pull down the latest code I pushed, use `.configure(rest(url).axios(axios))` instead of the `.configure(socketio(socket))` in `feathers.service.js` under app/services/api. Then in your chrome developer tools (cmd + option + i) you can visit the network tab before you make the request and see.

It looks like the feathers.logout method doesn't send an api request, it just destroys the local cookie and user information client side.

For forgot password its

`http://localhost:3030/api/authManagement`
`POST`
Headers: Authorization: token
Data: {
  "action": "sendResetPwd",
  "value": {
    "email": "your email"
  }
}
